Update relrsapps.yml

diff --git a/.github/workflows/relrsapps.yml b/.github/workflows/relrsapps.yml
--- a/.github/workflows/relrsapps.yml
+++ b/.github/workflows/relrsapps.yml
@@ -85,19 +85,19 @@ jobs:
           repo_name=$(basename "$repo")
           echo "Checking for release directory in $repo_name"
           if [ -d "$repo_name/release" ]; then
-            echo "Copying binaries from $repo/target/release"
+            echo "Copying binaries from $reporelease"
             mkdir -p "build-artifacts/${{ matrix.os }}/$repo_name"
-            #cp -r "$repo/target/release/"* "build-artifacts/${{ matrix.os }}/$repo_name/" #stupid dont need folder anymore
-            cp "$repo/release/"* "build-artifacts/${{ matrix.os }}/$repo_name" >/dev/null || : #https://serverfault.com/questions/153875/how-to-let-cp-command-dont-fire-an-error-when-source-file-does-not-exist#153893
+            #cp -r "$repo_name/target/release/"* "build-artifacts/${{ matrix.os }}/$repo_name/" #stupid dont need folder anymore
+            cp "$repo_name/release/"* "build-artifacts/${{ matrix.os }}/$repo_name" >/dev/null || : #https://serverfault.com/questions/153875/how-to-let-cp-command-dont-fire-an-error-when-source-file-does-not-exist#153893
             cd "build-artifacts/${{ matrix.os }}/$repo_name"
             zip "../../binaries-ubuntu-latest.zip" ./
           else
-            echo "Release directory not found for $repo_name"
-            cd build-artifacts/${{ matrix.os }}
+            echo "Release directory not found for $repo_name"#DO NOT PACK HERE.correct repo name? build-artifacts/
+            #cd build-artifacts/${{ matrix.os }}
             # Print the contents of the directory
-            echo "Contents of build-artifacts directory:"
-            ls -al
-            zip -r "../../binaries-ubuntu-latest.zip" ./
+            #echo "Contents of build-artifacts directory:"
+            #ls -al
+            #zip -r "../../binaries-ubuntu-latest.zip" ./
           fi
         done
         # Print the contents of the directory
